// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://yidzdsnryogjlmxegorr.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZHpkc25yeW9namxteGVnb3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5MDI0OTYsImV4cCI6MjA0ODQ3ODQ5Nn0.QNpkRbNNAv-O-cwt5Iz91o6FpQn7zS2vlQoV5Ghk2Kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);